"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	 1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	   	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from HelperFunctions import is_pentagonal, is_triangle_number


index = 0
while True:
    # walk the hexagonal numbers until a solution is found
    i = index * (2 * index - 1)
    if is_triangle_number(i) and is_pentagonal(i) and i > 40755:
        print(i)
        break
    index += 1


