"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math


def divisors(num):
    if num == 1:
        return [1]
    divisor_list = list()
    for i in range(1, math.ceil(math.sqrt(num)) + 1):
        if num % i == 0:
            divisor_list.append(i)
            divisor_list.append(int(num / i))
    return list(set(divisor_list))


def triangle_number(index):
    return sum(range(1, index+1))


def main():
    index = 1
    while len(divisors(triangle_number(index))) <= 500:
        index += 1
        print(index)

    print(triangle_number(index))


if __name__ == '__main__':
    main()



